version: '3.8'

services:
  tiuos:
    build:
      context: .
      args:
        - NEXT_PUBLIC_DATA_MODE=live
        - NEXT_PUBLIC_DEFAULT_SERVER=tiuserver
        - NEXT_PUBLIC_SERVERS=[{"id":"tiuserver","name":"TiuServer","url":"https://api.tiuserver.my.id"}]
    container_name: tiuos
    restart: always
    ports:
      - "3010:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.tiuserver.my.id
    networks:
      - tiu-network

networks:
  tiu-network:
    external: true
