version: '3.8'

services:
  tiuos:
    build: .
    container_name: tiuos
    restart: always
    ports:
      - "3010:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.tiuserver.my.id
    networks:
      - tiu-network

networks:
  tiu-network:
    external: true
